Update workflow
Check for existing tag early in the release process

diff --git a/.github/workflows/release-and-deploy.yml b/.github/workflows/release-and-deploy.yml
--- a/.github/workflows/release-and-deploy.yml
+++ b/.github/workflows/release-and-deploy.yml
@@ -42,7 +42,7 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: debug secrets
+      - name: Debug secrets
         run: |
           echo Just to be sure, we check if we have access to the environment secrets:
           echo If line following this paragraph says, 'maven username: ***', it indicates that we can access
@@ -50,6 +50,23 @@ jobs:
           echo not work.
           echo 
           echo maven username: ${MAVEN_USERNAME}
+
+      # check if a tag already exists for the version we want to publish - in that case the workflow
+      # will fail later, so let us make it fail fast
+      - name: Check if tag ${{ inputs.release_version }} exists
+        uses: mukunku/tag-exists-action@v1.0.0
+        id: checkTag
+        with:
+          tag: ${{ inputs.release_version }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.QUDTLIB_BOT_GITHUB_TOKEN }}
+      - name: Fail if tag ${{ inputs.release_version }} exists
+        if: steps.checkTag.outputs.exists == 'true'
+        run: |
+          echo Tag ${{ inputs.release_version }} already exists, release aborted >> $GITHUB_STEP_SUMMARY
+          exit 1
+
+      # Set up java with maven cache
       - uses: actions/checkout@v3
       - name: Set up JDK 11
         uses: actions/setup-java@v3
@@ -128,6 +145,8 @@ jobs:
         with:
           token: ${{ secrets.QUDTLIB_BOT_GITHUB_TOKEN }}
           title: Release ${{ inputs.release_version }}
+          base: 'main'
+          branch: ${{ env.BRANCH_NAME }}
           body: |
             Automated release through workflow: '${{ github.workflow }}'
             Triggered by: ${{ github.triggering_actor }}
